import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import QueryProvider from "../components/QueryProvider";
import ToastProvider from "../components/ToastProvider";
import ThemeHydrationFix from "../components/ThemeHydrationFix";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "HRMS",
  description: "Generated by create next app",
};

const themeInitScript = `
  (function () {
    try {
      var storedTheme = localStorage.getItem("swiftrev.theme");
      var theme = (storedTheme === "dark" || storedTheme === "light")
        ? storedTheme
        : (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
      document.documentElement.classList.toggle("dark", theme === "dark");
      document.documentElement.dataset.theme = theme;
    } catch (error) {}
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white text-slate-900 antialiased dark:bg-slate-950 dark:text-slate-100`}
      >
        <ThemeHydrationFix />
        <QueryProvider>
          <ToastProvider />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
