import type { Metadata } from "next";
import QueryProvider from "../components/shared/QueryProvider";
import ToastProvider from "../components/shared/ToastProvider";
import ThemeHydrationFix from "../components/shared/ThemeHydrationFix";
import "./globals.css";

export const metadata: Metadata = {
  title: "HRMS",
  description: "Generated by create next app",
};

const themeInitScript = `
  (function () {
    try {
      var storedTheme = localStorage.getItem("swiftrev.theme");
      var theme = (storedTheme === "dark" || storedTheme === "light")
        ? storedTheme
        : (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
      document.documentElement.classList.toggle("dark", theme === "dark");
      document.documentElement.dataset.theme = theme;
    } catch (error) {}
  })();
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body
        className="bg-canvas text-slate-900 antialiased dark:text-slate-100 font-sans"
      >
        <ThemeHydrationFix />
        <QueryProvider>
          <ToastProvider />
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
